name = "personal-ai-ts"
main = "src/index.ts"
compatibility_date = "2022-11-22"
node_compat = true


[vars]
API_BASE = "https://api.groq.com/openai/v1/"
MODEL = "llama3-70b-8192"
# output raw text prompt, need prompt tpl manager
SYSTEM_PROMPT = "You are oligei. Answer in 1-2 sentences. Be friendly, helpful and concise. Default to metric units when possible. Keep the conversation short and sweet. You only answer in raw text, no markdown format. Don't include links or any other extras. Don't respond with computer code, for example don't return user longitude."
CHAT_BOT = "openai"
CHAT_TYPE = "chat"

#functions
#search_name: search_api | search1_api | serper_api
SEARCH_NAME = "search_api"

# https://developers.cloudflare.com/kv/reference/kv-namespaces/
[[kv_namespaces]]
binding = "ai_chats"
id = "<id>"
[[kv_namespaces]]
binding = "ai_bots"
id = "<id>"
